services:
  app:
    image: 10.47.0.221:5000/messenger-api:v1
    ports:
      - target: 8000
        published: 8007
    environment:
      - KRB5_KEYTAB=./prod9.keytab

  nginx:
    image: 10.47.0.221:5000/messenger-client:v1
    ports:
      - target: 80
        published: 8006
    depends_on:
      - app
